[workspace]
resolver = "2"
members = [
  "./noitarchiver_gui/src-tauri/",
  "noitarchiver_cmd",
  "noitarchiver_core",
]

[workspace.package]
version = "4.0.0"
edition = "2024"

[workspace.dependencies]
rust-i18n = "3.1.5"
