[workspace]
members = [ "noitarchiver_cmd","noitarchiver_core"]
resolver = "2"

[workspace.package]
version = "4.0.0"
authors = ["Xiaomony"]
edition = "2024"

[workspace.dependencies]
rust-i18n = "3.1.5"
