[package]
name = "noitarchiver_core"
version = "4.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
directories = "6.0.0"
fs2 = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
regex = "1.11.2"
